// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXdeED6VaMHsh_8tWl2ODTeP6sIuM88g',
    appId: '1:253763428896:web:f8719134fd7ee850d55245',
    messagingSenderId: '253763428896',
    projectId: 'cpugad-dappli',
    authDomain: 'cpugad-dappli.firebaseapp.com',
    storageBucket: 'cpugad-dappli.firebasestorage.app',
    measurementId: 'G-8YN2BLMG4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7AClHciBVeCAR5lpzbLwErBJ956ywKI',
    appId: '1:253763428896:android:033194e109f709e4d55245',
    messagingSenderId: '253763428896',
    projectId: 'cpugad-dappli',
    storageBucket: 'cpugad-dappli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6waVUkQ-aMRluCb1GNjg2IUJE9MTe4Q',
    appId: '1:253763428896:ios:8bb9b73407c915d5d55245',
    messagingSenderId: '253763428896',
    projectId: 'cpugad-dappli',
    storageBucket: 'cpugad-dappli.firebasestorage.app',
    iosBundleId: 'com.example.flilipinoFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE6waVUkQ-aMRluCb1GNjg2IUJE9MTe4Q',
    appId: '1:253763428896:ios:8bb9b73407c915d5d55245',
    messagingSenderId: '253763428896',
    projectId: 'cpugad-dappli',
    storageBucket: 'cpugad-dappli.firebasestorage.app',
    iosBundleId: 'com.example.flilipinoFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiXdeED6VaMHsh_8tWl2ODTeP6sIuM88g',
    appId: '1:253763428896:web:e84d9061d4071430d55245',
    messagingSenderId: '253763428896',
    projectId: 'cpugad-dappli',
    authDomain: 'cpugad-dappli.firebaseapp.com',
    storageBucket: 'cpugad-dappli.firebasestorage.app',
    measurementId: 'G-V125181L7R',
  );
}
