import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class AppTheme {
  static ThemeData dark = ThemeData(
    colorScheme: darkColorScheme,
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        foregroundColor: darkColorScheme.onPrimaryContainer,
        textStyle: const TextStyle(fontWeight: FontWeight.bold),
        backgroundColor: darkColorScheme.primaryContainer,
        padding: const EdgeInsets.symmetric(vertical: 24, horizontal: 48),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        elevation: 2,
      ),
    ),
    textTheme:
        GoogleFonts.poppinsTextTheme(ThemeData.dark().textTheme).copyWith(
      displayLarge: GoogleFonts.itim(fontSize: 48, fontWeight: FontWeight.bold),
      headlineLarge: TextStyle(
        fontSize: 24,
        fontWeight: FontWeight.normal,
        color: darkColorScheme.primary,
      ),
      headlineMedium: const TextStyle(
        fontSize: 24,
        fontWeight: FontWeight.bold,
      ),
      labelLarge: TextStyle(color: darkColorScheme.primary),
    ),
  );
}

/// Light [ColorScheme] made with FlexColorScheme v8.2.0.
/// Requires Flutter 3.22.0 or later.
const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF745B00),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFF0C105),
  onPrimaryContainer: Color(0xFF140D00),
  primaryFixed: Color(0xFFFFE6A5),
  primaryFixedDim: Color(0xFFFCCC1C),
  onPrimaryFixed: Color(0xFF1A1200),
  onPrimaryFixedVariant: Color(0xFF281E00),
  secondary: Color(0xFF7F8BD8),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE5E6FF),
  onSecondaryContainer: Color(0xFF000F5C),
  secondaryFixed: Color(0xFFE5E6FF),
  secondaryFixedDim: Color(0xFFC9CFFF),
  onSecondaryFixed: Color(0xFF000947),
  onSecondaryFixedVariant: Color(0xFF051560),
  tertiary: Color(0xFF188943),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFC5FFCA),
  onTertiaryContainer: Color(0xFF001806),
  tertiaryFixed: Color(0xFF96FFAB),
  tertiaryFixedDim: Color(0xFF80E796),
  onTertiaryFixed: Color(0xFF001806),
  onTertiaryFixedVariant: Color(0xFF00260D),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFE4E8FE),
  onSurface: Color(0xFF131315),
  surfaceDim: Color(0xFFC6C8E0),
  surfaceBright: Color(0xFFE1E2FA),
  surfaceContainerLowest: Color(0xFFE4E8FE),
  surfaceContainerLow: Color(0xFFDCDEF5),
  surfaceContainer: Color(0xFFD7D9F1),
  surfaceContainerHigh: Color(0xFFD3D4EB),
  surfaceContainerHighest: Color(0xFFCECEE6),
  onSurfaceVariant: Color(0xFF1B1B1F),
  outline: Color(0xFF47464A),
  outlineVariant: Color(0xFFACAAAF),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFF353950),
  onInverseSurface: Color(0xFFFCF8FA),
  inversePrimary: Color(0xFFFFE089),
  surfaceTint: Color(0xFF4E68F9),
);

/// Dark [ColorScheme] made with FlexColorScheme v8.2.0.
/// Requires Flutter 3.22.0 or later.
const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFF0C105),
  onPrimary: Color(0xFF281E00),
  primaryContainer: Color(0xFFFFC400),
  onPrimaryContainer: Color(0xFF000000),
  primaryFixed: Color(0xFFFFE6A5),
  primaryFixedDim: Color(0xFFFCCC1C),
  onPrimaryFixed: Color(0xFF1A1200),
  onPrimaryFixedVariant: Color(0xFF281E00),
  secondary: Color(0xFF9AA6F5),
  onSecondary: Color(0xFF00063A),
  secondaryContainer: Color(0xFF6672BD),
  onSecondaryContainer: Color(0xFFF4F2FF),
  secondaryFixed: Color(0xFFE5E6FF),
  secondaryFixedDim: Color(0xFFC9CFFF),
  onSecondaryFixed: Color(0xFF000947),
  onSecondaryFixedVariant: Color(0xFF051560),
  tertiary: Color(0xFF88F09E),
  onTertiary: Color(0xFF001505),
  tertiaryContainer: Color(0xFF005324),
  onTertiaryContainer: Color(0xFF96FFAB),
  tertiaryFixed: Color(0xFF96FFAB),
  tertiaryFixedDim: Color(0xFF80E796),
  onTertiaryFixed: Color(0xFF001806),
  onTertiaryFixedVariant: Color(0xFF00260D),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF310001),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFEDEA),
  surface: Color(0xFF0F151A),
  onSurface: Color(0xFFF2F0F1),
  surfaceDim: Color(0xFF0F151A),
  surfaceBright: Color(0xFF2D3338),
  surfaceContainerLowest: Color(0xFF0A1116),
  surfaceContainerLow: Color(0xFF151C21),
  surfaceContainer: Color(0xFF192024),
  surfaceContainerHigh: Color(0xFF21282C),
  surfaceContainerHighest: Color(0xFF293035),
  onSurfaceVariant: Color(0xFFE2E2E5),
  outline: Color(0xFF8F9193),
  outlineVariant: Color(0xFF5D5E61),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFFB6BABE),
  onInverseSurface: Color(0xFF1B1C1D),
  inversePrimary: Color(0xFF745B00),
  surfaceTint: Color(0xFF001E2F),
);
